### ISSUE TITLE
create .gitignore

### ISSUE THREAD

**Issue by leahcimto** [ScratchEmbed/scratchembed.github.io#4]
create it and include .DS_Store and other files to be ignored

**Comment by leahcimto** [comment]
@Accio1

**Comment by Accio1** [comment]
Thanks, I will include this in the next round of updates.

**Comment by leahcimto** [comment]
also, if you are going to use vue you might want to include this:

(i just searched that up though)

node_modules/
/dist
/public

# Log files
npm-debug.log*
yarn-debug.log*
yarn-error.log*

**Comment by Accio1** [comment]
I think that is if you are including vue by downloading it. If you use a CDN, which is what I am leaning towards, I don't think you need to include those files.

**Comment by leahcimto** [comment]
Ok
