### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by Accio1** [ScratchEmbed/scratchembed.github.io#9]
This repo needs issue and PR templates, similar to the ones used by The Forum Helpers organization.

**Issue Templates:**
- Bug
- Feature
- Documentation
- Blank

**PR Templates:**
- Only one is allowed, but the headings should be the same as The Forum Helpers template.

**Comment by Accio1** [comment]
@leahcimto would you be interested in working on this?

**Comment by leahcimto** [comment]
@Accio1 Yep, I would.

**Comment by leahcimto** [comment]
@Accio1 Would you like to be assigned to all of the issues by default, or would you like no one assigned to prevent confusion on who is working on what.

**Comment by Accio1** [comment]
For now, assign no one. Hopefully as this organization grows, we will be able to pick who gets assigned to which issues.

**Comment by leahcimto** [comment]
@Accio1 Would you like me to convert these labels to the style tfh has and add the labels that are applicable here?

**Comment by Accio1** [comment]
@leahcimto, yes, that would be great!

**Comment by leahcimto** [comment]
Got it! I like the transparent logo btw

**Comment by Accio1** [comment]
@leahcimto any progress on this? (no rush if you are busy)

**Comment by leahcimto** [comment]
Sorry for the delay, I forgot about this. I currently don’t have access to a computer so I’m on a tablet, but will start the labels now.

**Comment by leahcimto** [comment]
@Accio1 done with the labels, will get to templates ASAP. One question, when would labels like `type: HTML` and `type: CSS` be used?

**Comment by Accio1** [comment]
@leahcimto actually, I think those could go ahead and be deleted. They're not as useful as I thought they would be when I made them.

**Comment by leahcimto** [comment]
I hope to have the pr up today, sorry for the delay.

**Comment by Accio1** [comment]
Resolved by #10

**Comment by leahcimto** [comment]
I guess I'll close this then

**Comment by Accio1** [comment]
> I guess I'll close this then

Whoops, forgot to close! Thanks!
